spring.datasource.url=jdbc:mysql://mysql.us.cloudlogin.co/gamabasis_laboratoriop1_5
spring.datasource.username=gamabasis_laboratoriop1_5
spring.datasource.password=Bx39Ots9K*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=3306